import { useMemo, useState } from 'react'
import { ArrowUpRight, Bell, CalendarDays, Check, ChevronRight, Clock3, Heart, Leaf, Menu, Plus, Search, Sparkles, Star, Users, X } from 'lucide-react'
import './index.css'

const people = [
  { name:'陈宇', role:'数据分析师 · 上海', avatar:'CY', teach:['Python','数据分析'], want:['手机摄影'], score:94, next:'周六 20:00', color:'blue', intro:'把复杂的数据讲得像搭积木一样简单。', rating:'4.9' },
  { name:'周宁', role:'独立摄影师 · 上海', avatar:'ZN', teach:['人像摄影','Lightroom'], want:['Python 入门'], score:89, next:'周三 19:30', color:'yellow', intro:'喜欢把每一次练习，都变成看得见的作品。', rating:'5.0' },
  { name:'王可', role:'内容创作者 · 杭州', avatar:'WK', teach:['英语口语','脚本写作'], want:['视频剪辑'], score:82, next:'周日 10:00', color:'pink', intro:'用真实场景学语言，用内容记录成长。', rating:'4.8' },
]

function App(){
  const [page,setPage]=useState('discover'), [query,setQuery]=useState(''), [selected,setSelected]=useState(null), [create,setCreate]=useState(false), [sent,setSent]=useState(false), [saved,setSaved]=useState([]), [toast,setToast]=useState('')
  const list=useMemo(()=>people.filter(p=>`${p.name}${p.teach.join('')}${p.want.join('')}`.toLowerCase().includes(query.toLowerCase())),[query])
  const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2400)}
  return <div className="app"><div className="grain"/>
    <header className="topbar"><button className="brand" onClick={()=>setPage('discover')}><span className="brand-mark"><Leaf size={16}/></span>skill<span className="dot">·</span>swap</button><nav><button className={page==='discover'?'active':''} onClick={()=>setPage('discover')}>发现伙伴</button><button className={page==='plans'?'active':''} onClick={()=>setPage('plans')}>我的计划 <b>1</b></button><button className={page==='about'?'active':''} onClick={()=>setPage('about')}>怎么开始</button></nav><div className="top-actions"><button className="icon"><Bell size={18}/></button><button className="profile"><span>LY</span>林晓雨<ChevronRight size={14}/></button><Menu className="menu" size={20}/></div></header>
    {page==='discover'&&<>
      <section className="hero"><div className="hero-copy"><div className="eyebrow"><i/> skill exchange club <span>技能互换社区</span></div><h1>把你会的，<br/><em>换成</em>你想学的。</h1><p>一场不花钱的双向学习。找到刚好互补的人，<br/>一起完成一个真正属于你们的作品。</p><div className="hero-actions"><button className="primary" onClick={()=>setCreate(true)}>开始我的交换 <ArrowUpRight size={17}/></button><button className="link" onClick={()=>document.getElementById('matches').scrollIntoView({behavior:'smooth'})}>先看看伙伴 <ChevronRight size={16}/></button></div><div className="proof"><div className="avatars"><span>CY</span><span>ZN</span><span>WK</span><span>+2k</span></div><div><b>2,184</b><small>位学习伙伴正在交换</small></div></div></div><div className="hero-art"><div className="orbit one"/><div className="orbit two"/><div className="swap-card"><div className="card-line"><span className="live">● 现在活跃</span><small>交换 #0248</small></div><div className="pair"><div><div className="portrait blue">CY</div><strong>陈宇</strong><small>Python / 数据</small></div><div className="swap"><i>↗</i><span><Sparkles size={16}/></span><i>↙</i></div><div><div className="portrait pink">LY</div><strong>林晓雨</strong><small>手机摄影</small></div></div><hr/><p><Sparkles size={14}/> <b>94% 匹配</b> · 你们都在周六晚上有空</p></div><div className="note yellow"><b>✦ 一起完成</b><small>一个数据分析作品</small></div><div className="note pink"><div><span>ZN</span><span>WK</span><span>+</span></div><small>本周已有 38 次交换</small></div><span className="star">✳</span></div></section>
      <div className="marquee"><div>摄影　✳　Python　✳　英语口语　✳　视频剪辑　✳　插画　✳　摄影　✳　Python　✳　</div></div>
      <section className="section" id="matches"><div className="section-head"><div><label>为你挑的伙伴</label><h2>今天，和谁交换？</h2></div><div className="tools"><div className="search"><Search size={16}/><input placeholder="搜索技能或名字" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="filter">筛选 <b>3</b></button></div></div><div className="grid">{list.map((p,i)=><article className={`match ${p.color}`} key={p.name} style={{'--delay':`${i*70}ms`}}><div className="match-top"><span>{p.score}% 匹配</span><button onClick={()=>setSaved(s=>s.includes(p.name)?s.filter(x=>x!==p.name):[...s,p.name])}><Heart size={18} fill={saved.includes(p.name)?'currentColor':'none'}/></button></div><div className="person"><div className={`avatar ${p.color}`}>{p.avatar}</div><div><h3>{p.name}</h3><small>{p.role}</small></div></div><p className="quote">“{p.intro}”</p><div className="skills"><div><label>能教</label>{p.teach.map(x=><span key={x}>{x}</span>)}</div><div><label>想学</label>{p.want.map(x=><span key={x}>{x}</span>)}</div></div><div className="meta"><span><Clock3 size={14}/> {p.next}</span><span><Star size={14} fill="currentColor"/> {p.rating}</span></div><button className="card-btn" onClick={()=>{setSelected(p);setSent(false)}}>查看交换可能 <ArrowUpRight size={16}/></button></article>)}</div><button className="load" onClick={()=>notify('更多伙伴正在赶来，先完善你的技能名片吧')}>探索更多伙伴 <ArrowUpRight size={16}/></button></section>
      <section className="section dark"><div className="section-head"><div><label>很简单，三步开始</label><h2>让学习变成一件<br/><em>有人陪你做完</em>的事。</h2></div><p>没有课程售卖，没有复杂的社交套路。<br/>只有两个刚好互补的人，和一个想完成的目标。</p></div><div className="steps">{[['01',Plus,'写下你的交换愿望','告诉我们你能教什么，也告诉我们你真正想学会什么。'],['02',Users,'遇见刚好互补的人','系统会解释每一次推荐，让匹配变得有理由、有温度。'],['03',Sparkles,'一起完成一个成果','从第一次交流到最终作品，每一步都有清晰的下一步。']].map(([n,Icon,t,d])=><div className="step" key={n}><label>{n}</label><Icon/><h3>{t}</h3><p>{d}</p><ArrowUpRight className="corner" size={18}/></div>)}</div></section>
      <section className="quote-section"><div className="quote-mark">“</div><blockquote>我本来只是想学会 Python，<br/>最后收获的是一个真的完成了的作品，<br/><em>和一个愿意继续一起学习的人。</em></blockquote><div className="quote-by"><span>LY</span><div><b>林晓雨</b><small>完成第 1 次技能交换后</small></div></div></section>
    </>}
    {page==='plans'&&<section className="page"><label>我的学习轨迹</label><h1>交换计划 <small>01</small></h1><p>每一次交换，都会留下一个看得见的成果。</p><div className="plan"><div className="plan-head"><div className="plan-avatars"><span>CY</span><span>LY</span></div><div><label className="status">● 进行中 · 第 2 周</label><h2>摄影 × Python 数据分析</h2><p>和陈宇的 4 周技能交换计划</p></div><div className="progress">42%<small>已完成</small></div></div><div className="timeline">{['确定目标与学习环境','数据处理基础 × 人像构图','完成第一份可视化图表','提交最终作品并互评'].map((t,i)=><div className={i<2?'done':''} key={t}><span>{i<2?<Check size={13}/>:i+1}</span><div><b>{t}</b><small>{i===1?'本周任务 · 截止周日':i<1?'已完成':'待解锁'}</small></div><ChevronRight size={16}/></div>)}</div><button className="primary" onClick={()=>notify('已打开本周任务清单')}>继续本周任务 <ArrowUpRight size={16}/></button></div></section>}
    {page==='about'&&<section className="page about"><label>关于 skill·swap</label><h1>把交换，变成<br/><em>成长的证据。</em></h1><p className="large">我们相信，每个人身上都有一项可以帮助别人的技能；每个人也都值得被另一个人认真带着走一段。</p><div className="manifesto">{[['01','双向，而不是单向','你不是来购买一门课，也不是来当一个老师。你们各自带着一项能力，交换一段真实的成长。'],['02','有目标，才有完成','从“我想学摄影”变成“我想拍出一组人像”，目标越具体，交换越容易发生。'],['03','做出东西，才算学会','每一次计划都会以一个作品、一项任务或一份可分享的成果结束。']].map(x=><div key={x[0]}><label>{x[0]}</label><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>}
    <footer><button className="brand"><span className="brand-mark"><Leaf size={14}/></span>skill<span className="dot">·</span>swap</button><span>让技能流动起来，让成长有人陪。</span><span>© 2025 SkillSwap Club</span></footer>
    {selected&&<div className="backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X size={18}/></button><div className="modal-person"><div className={`avatar ${selected.color}`}>{selected.avatar}</div><div><span className="score">{selected.score}% 匹配</span><h2>{selected.name} <i/></h2><p>{selected.role}</p></div></div><div className="reason"><Sparkles size={16}/><p><b>为什么推荐你们？</b><br/>你想学数据分析，而 {selected.name} 正好擅长 Python；对方想学摄影，和你的技能形成互补。</p></div><div className="exchange"><div><small>你提供</small><b>手机摄影</b></div><strong>↔</strong><div><small>你获得</small><b>{selected.teach[0]}</b></div></div>{sent?<div className="success"><span><Check/></span><h3>交换邀请已发送</h3><p>等对方确认后，你们会自动拥有一个 4 周学习计划。</p><button className="primary" onClick={()=>setSelected(null)}>好的，去看看我的计划</button></div>:<button className="primary full" onClick={()=>{setSent(true);notify('交换邀请已发送')}}>发起交换邀请 <ArrowUpRight size={17}/></button>}</div></div>}
    {create&&<div className="backdrop" onClick={()=>setCreate(false)}><div className="modal create" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setCreate(false)}><X size={18}/></button><label>创建你的技能名片</label><h2>你想拿什么，<em>换什么？</em></h2><div className="form-row"><label>我能教<input placeholder="例如：手机摄影、Excel..."/></label><label>我想学<input placeholder="例如：Python、吉他..."/></label></div><label className="full-label">我想完成的目标<textarea placeholder="例如：4 周内完成一个销售数据分析项目" rows="3"/></label><div className="chips"><button>线上 / 线下都可以</button><button>每周 1 小时</button><button>上海</button></div><button className="primary full" onClick={()=>{setCreate(false);notify('技能名片已保存，正在为你寻找伙伴')}}>生成我的匹配 <ArrowUpRight size={17}/></button></div></div>}
    {toast&&<div className="toast"><Check size={15}/>{toast}</div>}
  </div>
}
export default App
